const center = [13.395, 52.517]; let selectedLocation = center; let pickingLocation = false;
const colors={pickpocket:'#e17840','fake-rental':'#d85555',ticket:'#7a5ac8',other:'#3183b6'}, icons={pickpocket:'!', 'fake-rental':'⌂',ticket:'↗',other:'i',police:'♜',hospital:'+',embassy:'▦',family:'★'}, placeColors={police:'#315783',hospital:'#ce5252',embassy:'#786a51',family:'#d59f38'}, names={pickpocket:'Pickpocketing','fake-rental':'Fake rental',ticket:'Ticket scam',other:'Other scam'};
const seed=[{type:'pickpocket',title:'Bag distraction near Warschauer Brücke',detail:'Two people created a distraction while a third reached for a backpack.',where:'Friedrichshain',time:'2 hours ago',lat:52.5054,lng:13.4504},{type:'fake-rental',title:'Deposit requested before viewing',detail:'A listing asked for a transfer before a viewing could be arranged.',where:'Neukölln',time:'Yesterday',lat:52.4819,lng:13.4311},{type:'ticket',title:'Counterfeit event tickets offered',detail:'Tickets were offered outside the venue with cash-only payment.',where:'Mitte',time:'2 days ago',lat:52.5201,lng:13.4049},{type:'other',title:'Card reader overcharge warning',detail:'Check the total before tapping at temporary market stalls.',where:'Kreuzberg',time:'3 days ago',lat:52.4988,lng:13.4194}];
const places=[{type:'police',name:'Polizei Abschnitt 57',detail:'Police station · Mitte',lat:52.5217,lng:13.3887},{type:'police',name:'Polizei Abschnitt 53',detail:'Police station · Friedrichshain',lat:52.5118,lng:13.443},{type:'hospital',name:'Charité Campus Mitte',detail:'Hospital · emergency services',lat:52.5267,lng:13.376},{type:'hospital',name:'Vivantes Klinikum Neukölln',detail:'Hospital · emergency services',lat:52.465,lng:13.442},{type:'embassy',name:'Embassy of the United Kingdom',detail:'Embassy · Tiergarten',lat:52.5164,lng:13.3653},{type:'embassy',name:'Embassy of the United States',detail:'Embassy · Mitte',lat:52.5161,lng:13.3503},{type:'family',name:'Museum für Naturkunde',detail:'Family-friendly museum',lat:52.5306,lng:13.3808},{type:'family',name:'FEZ Berlin',detail:'Family leisure centre',lat:52.4446,lng:13.529}];
let reports=[...seed,...JSON.parse(localStorage.getItem('saferStreetsReports')||'[]')], pins=[];
const map=new maplibregl.Map({container:'city-map',style:'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',center,zoom:11.7,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');
const active=(type,group)=>document.querySelector(`input[data-layer="${group}"][data-type="${type}"]`)?.checked;
function pop(item,isPlace){return `<p class="popup-type">${isPlace?'Trusted support':'Community report'}</p><p class="popup-title">${item.name||item.title}</p><p class="popup-detail">${item.detail}</p>`;}
function pin(item,isPlace=false){const el=document.createElement('button');el.type='button';el.className=`geo-marker ${isPlace?'support':'report'}`;el.style.background=isPlace?placeColors[item.type]:colors[item.type];el.textContent=icons[item.type];el.setAttribute('aria-label',item.name||item.title);return new maplibregl.Marker({element:el,anchor:'center'}).setLngLat([item.lng,item.lat]).setPopup(new maplibregl.Popup({offset:18,closeButton:false}).setHTML(pop(item,isPlace))).addTo(map);}
function drawMap(){pins.forEach(x=>x.remove());pins=[];reports.filter(r=>active(r.type,'scam')).forEach(r=>pins.push(pin(r)));places.filter(p=>active(p.type,'place')).forEach(p=>pins.push(pin(p,true)));}
function drawReports(){document.querySelector('#report-list').innerHTML=reports.slice(0,3).map(r=>`<div class="report-entry"><div class="report-icon" style="background:${colors[r.type]}">${icons[r.type]}</div><div class="report-copy"><b>${r.where} · ${names[r.type]}</b><span>${r.title} · ${r.time}</span></div></div>`).join('');}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3800);}
map.on('load',drawMap);map.on('click',e=>{selectedLocation=[e.lngLat.lng,e.lngLat.lat];document.querySelector('#pin-status').textContent=`Map pin: ${e.lngLat.lat.toFixed(4)}, ${e.lngLat.lng.toFixed(4)}`;if(pickingLocation){pickingLocation=false;map.getCanvas().style.cursor='';dialog.showModal();toast('Location pinned — finish your report.');}else toast('Map pin updated for your next report.');});
document.querySelectorAll('input[data-layer]').forEach(i=>i.onchange=drawMap);document.querySelector('#clear-filters').onclick=()=>{document.querySelectorAll('input[data-layer]').forEach(i=>i.checked=false);drawMap();};document.querySelector('#zoom-in').onclick=()=>map.zoomIn();document.querySelector('#zoom-out').onclick=()=>map.zoomOut();document.querySelector('#locate-button').onclick=()=>map.flyTo({center,zoom:11.7});
document.querySelector('#place-search').onkeydown=e=>{if(e.key!=='Enter')return;const q=e.target.value.toLowerCase(),target=[...reports,...places].find(x=>`${x.name||''} ${x.title||''} ${x.where||''}`.toLowerCase().includes(q));if(!target)return toast('Try Mitte, Neukölln, or Friedrichshain.');map.flyTo({center:[target.lng,target.lat],zoom:14});};
const dialog=document.querySelector('#report-dialog');document.querySelector('#open-report').onclick=()=>dialog.showModal();document.querySelector('#close-report').onclick=()=>dialog.close();document.querySelector('#use-map-center').onclick=()=>{const c=map.getCenter();selectedLocation=[c.lng,c.lat];document.querySelector('#pin-status').textContent=`Map pin: ${c.lat.toFixed(4)}, ${c.lng.toFixed(4)}`;};document.querySelector('#pick-on-map').onclick=()=>{pickingLocation=true;map.getCanvas().style.cursor='crosshair';dialog.close();toast('Pan anywhere, then click the exact location on the map.');};const details=document.querySelector('#scam-details');details.oninput=()=>document.querySelector('#count').textContent=details.value.length;
document.querySelector('#report-form').onsubmit=e=>{e.preventDefault();const type=document.querySelector('#scam-type').value,where=document.querySelector('#scam-location').value.trim(),raw=details.value.trim(),r={type,where,title:raw.slice(0,58)+(raw.length>58?'…':''),detail:raw,time:document.querySelector('#scam-time').value,lng:selectedLocation[0],lat:selectedLocation[1]};reports.unshift(r);localStorage.setItem('saferStreetsReports',JSON.stringify(reports.filter(x=>!seed.includes(x))));drawMap();drawReports();map.flyTo({center:[r.lng,r.lat],zoom:14});dialog.close();e.target.reset();document.querySelector('#count').textContent='0';toast('Thanks — your community report is now on this device’s map.');};document.querySelector('#next-report').onclick=()=>{reports.push(reports.shift());drawReports();};
